language: node_js
node_js:
  - "12"
# for code analysis sonarqube
git:
  depth: false
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - browny9532@gmail.com
  slack:
    on_success: always
    rooms: sideplatform-browny:0sTfK3iF7RiQFNRSZM0BHMQ7
script:
  - yarn install
  - yarn test

# before_deploy:
#   - serverless config credentials --provider aws --key AKIA5K7JOYXOPC54B7FE --secret 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

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: main
