language: node_js
node_js:
  - "12"
# for code analysis sonarqube
git:
  depth: false
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - browny9532@gmail.com
  slack:
    on_success: always
    rooms: sideplatform-browny:[token]
script:
  - yarn test

before_deploy:
  - serverless config credentials --provider aws --key [aws access key] --secret [aws secret key]
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: yarn deploy:prod
    on:
      branch: main