language: node_js
node_js:
  - "12"

# for code analysis sonarqube
git:
  depth: false

notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - browny9532@gmail.com
  # slack:
  #   on_success: always
  #   rooms:
  #   - 

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run deploy
    on:
      branch: master

  # tags deploy to prod environment
  # - provider: script
  #   skip_cleanup: true
  #   script: npm run deploy:prod
  #   on:
  #     tags: true
